"""add extracted_text to documents

Revision ID: 4c7fcd84a3e0
Revises: b73eedea6938
Create Date: 2026-07-16 11:07:26.101461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c7fcd84a3e0'
down_revision: Union[str, Sequence[str], None] = 'b73eedea6938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extracted_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'extracted_text')
    # ### end Alembic commands ###
